"""

Revision ID: 274c92aeae37
Revises: b13c53d0fe24
Create Date: 2020-09-09 11:18:14.077634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "274c92aeae37"
down_revision = "b13c53d0fe24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("candidates", sa.Column("avatar_path", sa.String(), nullable=True))
    op.create_unique_constraint(None, "candidates", ["avatar_path"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "candidates", type_="unique")
    op.drop_column("candidates", "avatar_path")
    # ### end Alembic commands ###
